# Generated by Django 4.2.6 on 2023-11-06 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_category_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='banner',
        ),
    ]
