# Generated by Django 4.2.6 on 2023-11-16 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_rename_cart_cartitem_cart_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='cart_item',
            new_name='cart',
        ),
    ]
